README.md
It's easier to read a list if all items in the list are grammatically similar.  All of the other items were verb phrases--which makes sense for goals!--so I changed the second item to also be a verb phrase by adding "be" to the beginning.
=> make all goals into verb phrases

guides/concurrency.md
Changed paragraph title in order to make it properly related to the underneath content.
=> Changed paragraph title

syntax_and_semantics/macros/hooks.md
=> Conform the method_missing example to Crystal 0.18

syntax_and_semantics/type_inference.md
This change has already been implemented.
=> Drop note about changes to type inference

syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.md
Fixed odd pairs of reference links.
=> Fix reference links in Method Argunents

using_the_compiler/README.md
We should stick to the coding conventions described here: https://crystal-lang.org/docs/conventions/coding_style.html#directory-and-file-names
=> Correct naming of sample project

README.md
I'd like to find contribution information fast if something bugs me in the documentation.
=> Add section about contribution

guides/performance.md
Fix word meaning. `help -> heap`.
=> fix word meaning

syntax_and_semantics/union_types.md
=> define union type at compile time

conventions/documenting_code.md
Pending Crystal PR **[3519](https://github.com/crystal-lang/crystal/pull/3519)**
=> Add documentation for doc flags

syntax_and_semantics/c_bindings/callbacks.md
See https://github.com/crystal-lang/crystal/issues/3140
=> Fix docs for Proc when passing it to C

installation/from_source_repository.md
This is an update for clarification from https://github.com/crystal-lang/crystal/issues/3605#issuecomment-263647886 as suggested by @bcardiff
=> update notes about running crystal after building from source

SUMMARY.md, installation/on_bash_on_ubuntu_on_windows.md
Instructions for testing Crystal on Bash on Ubuntu on Windows until we release a proper Windows version.
=> Bash on Ubuntu on Windows installation instructions

database/README.md
=> Adds note for pg driver

guides/concurrency.md
Grammar changes to improve the flow of the document.
=> Grammar changes [concurrency]

README.md
Just a small effort to help lower the barrier for contributing.
=> Adding a note about creating a page

README.md
Unaddressed comment on issue #8: use HTTPS instead of SSH
=> Add clone/cd instructions for building the book, replaces issue #8

installation/from_source_repository.md
Took this from https://github.com/crystal-lang/crystal/wiki/All-required-libraries which was referred to me by @sdogruyol
=> llvm version update to 3.8, 3.9 or 4.0.

README.md, guides/concurrency.md, guides/performance.md
Corrected "wont" to "won't"
Add a full stop at end of one list element
Removed extraneous French-style space
Added full stop to Knuth's full-sentence quote
Removed unnecessary initial "And"s
=> Some minor spelling, punctuation and style

syntax_and_semantics/if.md
Just a small tweak to the sentence flow after #88.
Sorry I didn't get this into #88, I forgot to check out the new wording before ti was merged.
=> Update sentence flow in if.md

installation/on_debian_and_ubuntu.md
Related to https://github.com/crystal-lang/crystal/issues/4342
=> Adding build-essentials step to installation guide

syntax_and_semantics/methods_and_instance_variables.md
(to function when copy-pasted)
=> Fixing example to be more complete

SUMMARY.md, installation/on_gentoo_linux.md
Not much to say; the title is self-explanatory.
=> Added installation guide for Gentoo Linux

syntax_and_semantics/and.md, syntax_and_semantics/or.md
I thought descriptive page titles might assist with searchability/indexing. 😄
=> Logical operator headings

syntax_and_semantics/overloading.md
When I tested this code I had an error with line 14. The error said "wrong number of arguments for `Person.new`" So I added some more code so the code would work and it worked, for those who are testing and learning the things I added was.
=> Convert this code so that is compiles

syntax_and_semantics/case.md
=> fixes #83, document then shorthand for case

using_the_compiler/README.md
Minor typo fix in compiler readme. Just something that caught my eye.
=> Minor typo fix

syntax_and_semantics/literals/integers.md
=> Add value range to Ints

syntax_and_semantics/constants.md
For issue #136 
I also added \_\_LINE__ but perhaps that is not needed. As always, comments and suggestions are welcome.
=> document magic constants

syntax_and_semantics/literals/string.md
Found a couple of typos in the String file.
=> Fix String Typos

SUMMARY.md, conventions/coding_style.md, guides/testing.md, syntax_and_semantics/requiring_files.md
=> Add a guide about testing

syntax_and_semantics/literals/string.md
It feels like #160 was merged way too fast... This fixes some mistakes that have been unnoticed.
I don't know... it's nice to get merged right away but maybe it would be better to give such PR's a few days time before merging (even if two core members approve) to give more time for others to review?
=> Fix errors in string literal

guides/performance.md
* Add docs about `String.build` vs `IO::Memory`
* New link to SO for heap vs stack memory
=> Add `String.build` performance recommendations

syntax_and_semantics/literals/string.md
=> Fix expected result as comment

guides/writing_shards.md
=> Change 3 characters

using_the_compiler/README.md
~~This adds instructions for static linking.
I've also included a little change to the link explaining heap/stack memory.~~
- Improve the title to reflect the dynamically-linked nature of the compiled executable 
- Create a section about binary size reduction
=> Add a section about binary size reduction

installation/from_source_repository.md
Fixes https://github.com/crystal-lang/crystal-book/issues/207
=> Updates LLVM Support Version

syntax_and_semantics/README.md
Fixes https://github.com/crystal-lang/crystal-book/issues/213
=> Added top level syntax & semantics ToC

syntax_and_semantics/break.md
=> Add explanation of break with parameter in break.md

syntax_and_semantics/if_var.md
Also improves some wording and markup in this section.
See crystal-lang/crystal#5834
=> Add details about variables used in a closure

syntax_and_semantics/macros.md
I wasn't able to find information about how to use "macro for" to iterate a specific amount of times, so I added a simple example.
=> Add example about numerical for iterating in macro

database/README.md
=> Fix some typos in database tutorial.

guides/testing.md
=> Fix link and repetition

syntax_and_semantics/literals/symbol.md
Add some explanations about symbol literals.
=> Overhaul symbol literal docs

overview/http_server.md
=> Use Crystal markdown instead of Ruby markdown

syntax_and_semantics/macros.md
Macros can be also used to generate classes and structs.
=> Add an example for macro classes

guides/performance.md
And some other minor fix and improvement.
=> Fix 404 link

syntax_and_semantics/literals/array.md
Fixes #271 and improves it a bit.
=> Fix examples in array.md

syntax_and_semantics/literals/range.md
I had no idea what that meant, so why not add a brief example.
=> Expand interval explanation

SUMMARY.md, installation/README.md, installation/on_alpine_linux.md, installation/on_freebsd.md
/cc @jirutka @myfreeweb please take a look, I might've missed something.
=> Add installation instructions on Alpine Linux and FreeBSD

using_the_compiler/README.md
Tried `--o` and got an error, `-o` is the correct flag in this case.
=> Fix typo `--o` should be `-o`

SUMMARY.md, syntax_and_semantics/literals/command.md
=> Add command literal

.travis.yml
[html-proofer](https://github.com/gjtorikian/html-proofer) automatically validates image, link and script references and helps detecting broken links.
=> Add html-proofer to .travis.yml

using_the_compiler/README.md
=> Add section about environment variables

syntax_and_semantics/visibility.md
=> Clarify visibility of protected methods

syntax_and_semantics/structs.md
More detailed explanation about passing by value and implications by that to mutable structs is given.
=> Improve structs.md

syntax_and_semantics/blocks_and_procs.md
=> Document the useage of &. with an argument

using_the_compiler/README.md
Introduced by crystal-lang/crystal#7562
/cc @bcardiff
=> Add documentation for CRYSTAL_LIBRARY_PATH

installation/from_source_repository.md
text change for llvm version support
=> text: removed llvm latest version support note

syntax_and_semantics/if_var.md
Closes https://github.com/crystal-lang/crystal/issues/7847
=> Clarify limitation of type restrictions to local variables

SUMMARY.md, syntax_and_semantics/offsetof.md
Implemented in https://github.com/crystal-lang/crystal/pull/7589
/cc @malte-v @asterite
=> Add documentation for offsetof

syntax_and_semantics/type_inference.md
Ye, I know, not a big deal, but in today's society, who knows?
=> Gender neutral pronoun

syntax_and_semantics/default_and_named_arguments.md
=> Fix typo in default_and_named_arguments.md

syntax_and_semantics/macros.md
Added the amazing verbatim macro method. Please review my explanation/wording. It may need some work.
=> Update macros to include verbatim

SUMMARY.md, database/connection.md
=> New DB Connection section

guides/testing.md, using_the_compiler/README.md
Based on the changes in https://github.com/crystal-lang/crystal/pull/8125, https://github.com/crystal-lang/crystal/pull/8310, and https://github.com/crystal-lang/crystal/pull/8068
=> Add docs for filters, focus, tags, and randomization of specs

syntax_and_semantics/operators.md
Followup on #370 
See https://github.com/crystal-lang/crystal-book/pull/370#discussion_r373879902
=> Fix logical operators stated as overloadable

SUMMARY.md, guides/ci/travis.md, guides/continuous_integration.md
Using TravisCI
Using CircleCI (coming soon)
=> New Continuous Integration section

conventions/documenting_code.md
Updates docs to include https://github.com/crystal-lang/crystal/pull/6989
=> Add section for inheriting documentation

.travis.yml
=> Allow external links to fail

using_the_compiler/README.md
These are a few typos that ~~I myself~~ my editor noticed.
=> Fix typos in using_the_compiler/README.md

.github/workflows/deploy-book.yml, Makefile, README.md
This simplifies instructions for local development and syncrhronizes with CI
environment.
=> Add Makefile

mkdocs.yml
Documentation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
=> Enable anchor links to headlines

docs/syntax_and_semantics/literals/string.md
Replace it with the biggest valid one
=> "\888" is not a valid octal

requirements.txt
See examples of what's currently wrongly highlighted in https://github.com/pygments/pygments/pull/1650 :D
=> Upgrade dependencies, now that Pygments improved Crystal support

docs/syntax_and_semantics/literals/string.md
Improves documentation on using heredocs as expression.
See crystal-lang/crystal#10268
=> Improve documentation on heredocs

docs/getting_started/cli.md
Updating link to ncurses shards
=> Updating link to shards

syntax_and_semantics/cross-compilation.md
I'm proposing some improvements to the pages on cross-compilation, based on my recent experience (and lack of experience), I think these changes will make it easier for others.  Happy to refactor to feedback.
=> Improve cross-compilation documentation.

docs/tutorials/basics/30_math.md
Fixes https://forum.crystal-lang.org/t/interactive-tutorial/3019/13?u=straight-shoota
=> Fix gcd example call

docs/assets/style.css
=> Fix z-index of carcin-play buttons

docs/assets/style.css
The underlying CSS classes changed
=> Restore the tweak to increase the header logo size

requirements.txt
=> Upgrade mkdocs-code-validator version

docs/syntax_and_semantics/requiring_files.md
Resolves https://github.com/crystal-lang/crystal/issues/10820
=> Remove documentation of incorrect lookup rule

docs/assets/style.css, docs/database/connection_pool.md, docs/getting_started/README.md, docs/getting_started/cli.md, docs/guides/ci/README.md, docs/guides/ci/circleci.md, docs/guides/ci/gh-actions.md, docs/guides/performance.md, docs/syntax_and_semantics/requiring_files.md, docs/syntax_and_semantics/visibility.md, requirements.in, requirements.txt
\+ rely on the more direct ability to add a title
=> Upgrade version of mkdocs-material and others

mkdocs.yml
=> Delete reference to missing script.js

docs/SUMMARY.md, docs/syntax_and_semantics/autocasting.md, docs/syntax_and_semantics/compile_time_flags.md
Perfection is the enemy of good (but comments are welcomed).
=> Adding autocasting

docs/syntax_and_semantics/literals/integers.md
PR #577 added Int128 and UInt128 to the table, but didn't update the preamble.
=> Fix typo "four" -> "five" in integers.md

docs/syntax_and_semantics/requiring_files.md
=> Enhance and clarify explanation of `CRYSTAL_ENV` lookup paths

docs/guides/static_linking.md
Adds a section on identifying static dependencies plus a few minor tweaks to existing content.
=> Improve static linking guide

docs/guides/hosting/gitlab.md, docs/guides/writing_shards.md
=> Remove references to crystalshards.xyz

.github/workflows/deploy-config.yml
Avoid running it on other repos
=> Limitting `Deploy config` action

docs/README.md
To be merged after https://github.com/crystal-lang/crystal-website/pull/327
=> Link to external resources

docs/syntax_and_semantics/documenting_code.md
=> Fix a typo

docs/crystal_for_rubyists/metaprogramming_help.md
The code was not properly linted and CI was failing because of this.
=> Fixing code linting

docs/syntax_and_semantics/platform_support.md
Update minimum supported FreeBSD version after https://github.com/crystal-lang/crystal/pull/12612
=> Update minimum supported FreeBSD version

docs/syntax_and_semantics/and.md, docs/syntax_and_semantics/or.md
ref https://github.com/crystal-lang/crystal-book/pull/652#issuecomment-1314136444
=> Improve examples for AND and OR

docs/man/crystal/README.md
Statical should have been statically.
=> Fixes spelling error

docs/syntax_and_semantics/type_restrictions.md
=> Document splat restrictions

docs/syntax_and_semantics/platform_support.md
Solves https://github.com/crystal-lang/crystal/issues/8732.
=> Promoting x86_64-linux-musl to Tier 1

docs/syntax_and_semantics/generics.md
Summary: Fixed a typo and wrote that generics are designed to achieve type polymorphism.
=> Better explain Generics

docs/getting_started/cli.md
"Got us covered" -> "has us covered"
=> Update cli.md with more natural wording

docs/syntax_and_semantics/macros/fresh_variables.md
Resolves https://github.com/crystal-lang/crystal-book/issues/142#issuecomment-1738370366
=> Fix example for fresh variables

docs/man/crystal/README.md
These tools were added in these PRs: 
* https://github.com/crystal-lang/crystal/pull/13631
* https://github.com/crystal-lang/crystal/pull/13783
=> Add manual entries for `tool dependencies` and `tool unreachable`

docs/syntax_and_semantics/platform_support.md
Depends on crystal-lang/crystal#13884
=> Update Android API level

docs/syntax_and_semantics/type_grammar.md
=> Add links to `alignof` and `instance_alignof`

.github/workflows/deploy-config.yml
Ref https://github.com/crystal-lang/crystal-book/pull/739#issuecomment-1912134672
=> Fix `deploy-config.yml` workflow

docs/syntax_and_semantics/enum.md
=> Fix typos in `enum.md`

.gitignore, docs/syntax_and_semantics/annotations/README.md
Long overdue mention of https://github.com/crystal-lang/crystal/pull/9326.
=> Mention argless `#annotations` method in annotation docs

docs/guides/testing.md
Mention there are more parameters and where to find them.
=> Add reference to compiler manual in Testing Guide

docs/man/crystal/README.md
Try to clarify that multiple locations are allowed.
=> Update spec parameters

docs/man/required_libraries.md
Friendly PR to correct TLS section typo.
=> Fix typo in required libraries TLS section

docs/syntax_and_semantics/c_bindings/enum.md
=> Fix `lib` `enum` code example

docs/syntax_and_semantics/exception_handling.md
=> Add suffix forms of `rescue` and `ensure`

docs/syntax_and_semantics/c_bindings/struct.md
=> Add `include` info to c-binding's `struct`

docs/man/required_libraries.md, docs/syntax_and_semantics/platform_support.md
Depends on crystal-lang/crystal#15195.
=> Document MSYS2 MINGW64 environment support

docs/syntax_and_semantics/compile_time_flags.md
=> Add trailing pipes in md tables

docs/database/transactions.md
- Remove duplicated lines that did not make sense
=> Fix DB transactions guide

docs/man/required_libraries.md
Ref https://github.com/crystal-lang/crystal/issues/15619
=> Add warning about Apple's libxml

mkdocs.yml
https://github.com/crystal-lang/crystal-website/issues/290#issuecomment-2866465143
=> Change link in logo to Crystal homepage

docs/SUMMARY.md
https://github.com/crystal-lang/crystal-website/issues/290#issuecomment-2866465143
=> Change nav link label from _Welcome_ to _Index_

.github/workflows/lint.yml
This is identical to https://github.com/crystal-lang/crystal-website/pull/926
=> [CI] Add pre-commit lint workflow
