crystal-lang/crystal-book

syntax_and_semantics/c_bindings/union.md

Just fixed a typo on the union type name.

Fixed typo

---

syntax_and_semantics/c_bindings/struct.md

As a matter of fact, the current code will error with a double declaration of `Node`. I have also updated the example to something a bit more relevant.

Recursive C structs do not need a forward declaration

---

installation/from_source_repository.md

The `contributing` link on the installation from sources page was broken, this PR just fixes it.

Fix contributing link on source installation page.

---

overview/http_server.md

Triggered by discussion on: https://github.com/crystal-lang/crystal/issues/3382

Update HTTP server example to show it listens on 127.0.0.1 by default

---

syntax_and_semantics/assignment.md
syntax_and_semantics/attributes.md
syntax_and_semantics/c_bindings/fun.md
syntax_and_semantics/case.md
syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.md
syntax_and_semantics/enum.md
syntax_and_semantics/exception_handling.md
syntax_and_semantics/literals/bool.md
syntax_and_semantics/literals/char.md
syntax_and_semantics/literals/floats.md
syntax_and_semantics/literals/hash.md
syntax_and_semantics/literals/named_tuple.md
syntax_and_semantics/literals/nil.md
syntax_and_semantics/literals/string.md
syntax_and_semantics/literals/tuple.md
syntax_and_semantics/not.md
syntax_and_semantics/requiring_files.md
syntax_and_semantics/visibility.md

Although there are probably a few typos left, most of the ones in `syntax_and_schemantics` have been fixed. I've also taken the liberty to reword a few sentences, but no major other changes.

Various typo and grammar fixes

---

SUMMARY.md
database/README.md

This adds a Database section before the performance and concurrency guides.
Explains only the very basics of crystal db.
I think it will make sense to later add subsections inside database/ folder for
* Connection pool 
* Prepared statements 
* Transactions
Meanwhile this can be published after review IMO.

basic crystal-db usage

---

syntax_and_semantics/methods_and_instance_variables.md

This is a PR that represents something discussed in https://github.com/crystal-lang/crystal-book/issues/47...
The [methods_and_instance_variables.md](https://github.com/crystal-lang/crystal-book/blob/master/syntax_and_semantics/methods_and_instance_variables.md) there's a code snippet:
```crystal
class Person
def initialize(@name : String)
@age = 0
end
end
```
Followed by:
> Right now, we can't do much with a person: create it with a name, ask for its name and for its age, which will always be zero. So lets add a method that makes a person become older:
But - really - we can't query the state of `@age` or `@name` without using `getter :age, :name`.
If you feel like this is big enough to address I can send a PR...perhaps...
> Right now, we can't do much with a person aside from create it …

Change wording about what we can do with a Person

---

README.md

I've seen first-hand new visitors see "build" and initially assume it is how to build/install the actual language, when in fact it is instructions on how to build the crystal-book project.
I think there are more improvements that can be made here too, but this initial change would be helpful.

Fixing confusion around the title "build"

---

syntax_and_semantics/if.md

Clear out confusion caused by `then` being used as branch name of `if` documentation.
Fixes crystal-lang/crystal#4117
Thank you. :heart: :heart: :heart:

Remove `then` branch in `if` documentation

---

syntax_and_semantics/finalize.md

Current documentation suggest `finalizer` might be used for regular code that developers might write.
The changes suggested here aims to indicate real world usage of `finalize` and include references from the standard library that showcase it's usage.
Also warn about possible undefined behavior when attempting to allocate memory during the garbage-collection phase.
Ref crystal-lang/crystal#4013
Thank you. :heart: :heart: :heart:

Add more real world usage of Object's finalizer

---

syntax_and_semantics/literals/char.md

Removed descriptions about octal escape from document of the Char literal.
It has already been removed at [v0.21.0](https://github.com/crystal-lang/crystal/releases/tag/0.21.0).

Removes octal escape from Char literal doc

---

syntax_and_semantics/type_grammar.md

Typeof isn't allowed in alias. Fixes crystal-lang/crystal#2849.

Fix typeof in alias

---

installation/on_bash_on_ubuntu_on_windows.md

In my installation using the subsystem, the progress display from curl was getting in the way of the sudo prompt, adding these flags fixed that issue.

Change curl comamnd in Bash on Ubuntu on Windows installation to include -sSL flags

---

syntax_and_semantics/case.md
syntax_and_semantics/operators.md

As discussed in crystal-lang/crystal#4295 there is no explanation for case equality in the docs. This tries to provide at least a simple understanding of this concept.

adds a short explanation for *case equality*

---

syntax_and_semantics/literals/string.md

While reading, I came across a small typo.

Fix typo: parenthesis => parentheses

---

syntax_and_semantics/methods_and_instance_variables.md

Relevant to #130, here is an initial stab at documenting the getters and setters macros and referencing the standard library. 
I see a couple problems with this I'd like to better approach before this gets merged, but I'm not sure what the documentation standards are around this type of thing. Hopefully a few minutes writing down concrete text will provide a place for concrete discussion on how to make it better. 
- Hard links to the standard library documentation at the current version are not forward compatible
- The placement of this section within the document is completely arbitrary. I couldn't find a place that felt natural to put it in. I'm open for suggestions.

Document getter, setter, and property macros

---

syntax_and_semantics/comments.md

The character used for comments is commonly referred to as the 'number sign,' not the 'sharp character' as was previously written.

Clarify Comment Page

---

syntax_and_semantics/exception_handling.md

relevant to #103 
I also toyed with the idea of explicitly stating that the `else` must come before the `ensure` but didn't find anything that pleased me, so I pulled it. 
Comments and suggestions welcome.

better document rescue/else/ensure ordering

---

syntax_and_semantics/literals/char.md
syntax_and_semantics/literals/string.md

Lunr.js can't handle emojis in the search index, this workaround encodes the emoji as html numerical character reference.
Unfortunately this woni't work inside fenced code blocks.
See #127 for details.

Workaround for corrupt search index

---

syntax_and_semantics/generics.md

Just a couple of small mistakes in the Generics file.

Fix Typos in Generics Description

---

syntax_and_semantics/requiring_files.md

This fixes #151 and clarifies the importance of the working directory when requiring files.

Clarify require docs and change libs to lib, fixes #151

---

guides/performance.md

gprof requires compiling code with an extra flag, which is only indirectly supported by crystal. Also, the gmon.out file produced sometimes ends up being empty. perf and callgrind are usually both more straightforward to use for new users and more powerful.
This PR is intended as an alternative to #147 (see discussion there for background).

Suggest perf/callgrind for profiling on Linux

---

conventions/documenting_code.md
guides/writing_shards.md

This pull request fixes parts of the documentation that still use `doc` instead of `docs`.

Change 'doc' to 'docs', fixes #158

---

syntax_and_semantics/literals/string.md

This PR improves the docs for string literals by adding explanations, improving wording, fixing some mistakes and generally making things clearer to understand.

Overhaul String literal docs

---

syntax_and_semantics/type_inference.md

The 2 subtitles in their original form seem like declarative instructive statements that contradict each other, rather than being just 2 different ways of doing something.

Improve subtitle phrasing

---

book.json

Adds edit links to each page using [edit-link](https://plugins.gitbook.com/plugin/edit-link) plugin.
Closes #89

Add gitbook plugin edit-link

---

.travis.yml

Fixup for #166 adding `gitbook install` to `.travis.yml`. This enables the use of the custom plugin.

Fixup #166: Add `gitbook install` to .travis.yml

---

README.md
overview/http_server.md

This supercedes https://github.com/crystal-lang/crystal-book/pull/86 because the author hasn't revisited it for 9 months.

Refer to this book as language reference instead of documentation

---

conventions/README.md
syntax_and_semantics/literals/string.md

This covers some typos originally fixed by https://github.com/crystal-lang/crystal-book/pull/86

Minor typos found by @WildYorkies

---

conventions/documenting_code.md

Change the expression return value indicator to include a space between `#` and `=>`, as per the examples that follow.

Add space to expression return value indicator

---

syntax_and_semantics/literals/nil.md

"not unlike" (a double negative) is harder for my brain to process than simply "similar to"

Improve wording of Nil explaination

---

syntax_and_semantics/literals/integers.md

#141 introduced incoherent table syntax which created an additional empty column. This PR removes the unneeded pipes at the end of line.

Fix GFM table syntax

---

using_the_compiler/README.md

The current compiler (0.24.1) commands print some differences in the output from what was documented here.

Update compiler output in `using_the_compiler`

---

syntax_and_semantics/compile_time_flags.md

When I was learning about flags, I had to manually figure out how to define them. This pull request adds a new section on how to define flags and changes some wording.  It should be easier to follow the examples now.

Various changes to compile_time_flags.md

---

syntax_and_semantics/literals.md

Avoids misinterpretation as Markdown table.
Fixes #192

Remove pipe from regex example

---

syntax_and_semantics/type_restrictions.md

This pull request adds a section demonstrating how Crystal handles type restricted variables inside the actual methods.
I want this section to be added, but the example could be much better than it is now. I'm not sure what to put there.

Clarify the type restrictions documentation

---

syntax_and_semantics/literals/string.md

The former one gave me the error: `String::Builder.new' is not expected to be invoked with a block, but a block was given`

Fix String::Builder example

---

syntax_and_semantics/multiple_assignment.md

This feature has been removed in 0.24.0  (see crystal-lang/crystal#4824)
Fixes crystal-lang/crystal#5793

Remove reference of bare array creation

---

syntax_and_semantics/pointerof.md

Right now this example gives you
```Crystal
Can't infer the type of instance variable '@x' of Point
def initialize(@x, @y)
^~
```

Fix wrong example in pointerof.md

---

syntax_and_semantics/c_bindings/fun.md

As of 0.24.0 function names in lib bindings can use upper case names (see crystal-lang/crystal#4934).
I also added two headings to structure the content of the page.

Fix c_bindings/fun can have upper case name

---

syntax_and_semantics/macros.md
syntax_and_semantics/macros/hooks.md

This adds examples of how the `method_missing` and `method_added` hooks work, especially which scopes they apply to.
I also added an example of `@type` being the same for instance and class methods.

Add more examples of macro hooks & @type

---

installation/on_mac_osx_using_homebrew.md

We [finally](https://github.com/Homebrew/homebrew-core/pull/29574#issuecomment-401548780) managed to rename the homebrew formula from `crystal-lang` to `crystal` 🎉
(whoever manages Linuxbrew, maybe they should rename the formula there too)

Homebrew formula was renamed from crystal-lang to crystal

---

syntax_and_semantics/literals/regex.md

Extends the documentation of regex literals. It contains some duplication from the recently overhauled string literal docs, but I think it is better to have the most important things here directly and more in-depth details can be handled in the string literal docs.
The part about unicode escapes is currently not accurate, see crystal-lang/crystal#5412 but this is how it *should* be.

Overhaul Regex literal docs

---

SUMMARY.md
installation/on_bash_on_ubuntu_on_windows.md
installation/on_debian_and_ubuntu.md

Installing Crystal on Windows Subsystem for Linux typically doesn't differ from installing on the respective native Linux platform. The only notable exception to that is only recently with Ubuntu 18.04, but not a big deal (see #259).
And WSL easily supports different Linux distributions, not just Ubuntu.
That's why I figure it doesn't make much sense to have detailed instructions for WSL but instead point to the respective Linux distribution's installation instructions.
Renamed `Bash on Ubuntu on Windows` to `Windows Subsystem for Linux` which is the proper and more general name. I left the path at `installation/on_bash_on_ubuntu_on_windows.md` to not break links. It could be moved and redirect, but I don't think it hurts much.
The assessment of *highly experimental*, is certainly not …

Remove redundancy in WSL instructions and improve for Debian/Ubuntu

---

using_the_compiler/README.md

Removed mention of crystal's "deps" command since this has been replaced by "shards".

Remove out-of-date mention of "deps"

---

installation/from_source_repository.md
installation/on_mac_osx_using_homebrew.md

The [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/71838be7661e2d48da00acb9d684b0eebea6e61f/Formula/crystal.rb) no longer supports the `--with-llvm` option.

Remove --with-llvm option from Homebrew instructions

---

SUMMARY.md
guides/performance.md
installation/README.md
installation/on_mac_osx_using_homebrew.md
syntax_and_semantics/c_bindings/lib.md

I intentionally haven’t updated the filename `on_mac_osx_using_homebrew.html` to keep existing links intact.

Update spelling of “macOS”

---

syntax_and_semantics/inheritance.md

Not sure about linking to an issue in the gitbook ... but otherwise, how's this for a crack at https://github.com/crystal-lang/crystal/issues/6507#issuecomment-411714904?

Update inheritance.md - covariance and contravariance

---

syntax_and_semantics/if_var.md

The example demonstrates a concurrent variable update case, which causes a non-deterministic runtime behavior. This commit changes the variable name defined in the upper scope and alternated in this clojure.

Fixed a variable name in the if-var concurrent clojure example

---

README.md
conventions/README.md
conventions/documenting_code.md
using_the_compiler/README.md

I think the `crystal docs` command could use a bit more documentation. Additionally, I noticed that the startup process for gitbook includes a `gitbook install` step so I threw that in here as well.

Add more documentation on the docs command

---

syntax_and_semantics/literals/string.md

The docs for this page are inconsistent in how they use the "result" expression comment
```crystal
```
In use is both the actual "representation" of the string, and how the string would be printed to the terminal.
A literal denoted by `%q` does not apply interpolation nor escapes while `%Q` has the same meaning as `%`.
```crystal
name = "world"
%q(hello \n #{name}) # => "hello \\n \#{name}"
%Q(hello \n #{name}) # => "hello \n world"
```
```crystal
Hello \n #{name}
Hello
world
```
To denote a heredoc without interpolation or escapes, the opening heredoc identifier is enclosed in single quotes:
```crystal
<<-'HERE'
hello \n #{world}
HERE # => "hello \n #{world}"
```
```crystal
hello \n #{world}
```
```crystal
<<-'HERE'
hello \n #{world}
HERE # => "hello \\n \#{world}"
```
However I think …

Reporting inconsistency in String docs

---

syntax_and_semantics/literals/string.md

On "Percent Array Literals" section on Array page, there's a link to "Percent String Array Literal", but this section is not available in String page now.
So, here is that missing section.

Find missing "Percent string array literal"

---

syntax_and_semantics/literals/regex.md

For some reason, this syntax is listed in the docs despite leading to an error like
```
Syntax error in regex-test.cr:12: invalid regex: PCRE does not support \L, \l, \N{name}, \U, or \u at 1
/\u1234/ # hexadecimal unicode character
^
```
The `\x{NNNN}` syntax seems to work fine however, so I've replaced the `\u` syntax with that.

Fix regex literal docs incorrectly listing \uNNNN syntax

---

installation/from_source_repository.md

According to the wiki (https://github.com/crystal-lang/crystal/wiki/All-required-libraries) as well as what actually happens if e.g. installing crystal through homebrew, llvm 6.0 is supported.

Add llvm@6.0 to list of supported libraries.

---

syntax_and_semantics/literals/range.md

There should be parentheses around the range before casting, because in this way, we try to cast the 5, not the whole range

Casting range to array code example fixed

---

syntax_and_semantics/c_bindings/callbacks.md

This change updates the passing a closure as callback example to the one listed in the API docs for [Proc](https://crystal-lang.org/api/0.27.0/Proc.html).
Basically... the type of `@@box` `Box(Int32 ->)` is actually a `Pointer(Void)?` now (or maybe it has always been that way?)

Update passing a closure as callback example

---

syntax_and_semantics/literals/range.md

Also includes documentation of begin-less and end-less ranges introduced by https://github.com/crystal-lang/crystal/pull/7179
/cc @asterite

Improve description of range literal

---

installation/on_debian_and_ubuntu.md

Without libz-dev, `crystal play` (later in the file) crashes with the error: 
/usr/bin/ld: cannot find -lz (this usually means you need to install the development package for libz)
collect2: error: ld returned 1 exit status

add libz-dev to recommended Debian/Ubuntu packages

---

installation/on_mac_osx_using_homebrew.md

I ran into this issue recently trying out crystal and hoped to contribute!
[crystal-7209](https://github.com/crystal-lang/crystal/issues/7209)

added a troubleshooting section for macOS mojave

---

syntax_and_semantics/modules.md

The supplied compiler output is wrong and confusing because Class actually has a 'new' method.

Fix the module instantiation example

---

syntax_and_semantics/next.md

Fixes #97 and documents that `next` can be used to exit from blocks.

Extend next's documentation

---

syntax_and_semantics/requiring_files.md

This takes into account the "src" directory inside shards.
Fixes #226

Update the way `require` works

---

using_the_compiler/README.md

Fix using the compiler typos while linking sections so desired section is properly linked.

Fix using the compiler typos

---

Dockerfile
book.json

Update docker to install fixed version directly
Otherwise there was an error bumping
```
crystal-book | info: 10 plugins are installed 
crystal-book | info: loading plugin "ga"... OK 
crystal-book | info: loading plugin "edit-link"... OK 
crystal-book | info: loading plugin "offline"... OK 
crystal-book | info: loading plugin "livereload"... OK 
crystal-book | info: loading plugin "highlight"... OK 
crystal-book | info: loading plugin "search"... OK 
crystal-book | info: loading plugin "lunr"... OK 
crystal-book | info: loading plugin "sharing"... OK 
crystal-book | info: loading plugin "fontsettings"... OK 
crystal-book | info: loading plugin "theme-default"... OK 
crystal-book | info: found 140 pages 
crystal-book | info: found 5 asset files 
crystal-book | 
crystal-book | Error: …
```

Fix gitbook version to 3.2.2

---

overview/http_server.md

When running this example I get:
>Warning: Deprecated Time.now. Use `Time.local` or `Time.utc` instead.
It works without warning when using Time.local instead.

Update http_server.md to use Time.local

---

using_the_compiler/README.md

There are a few flags that I wish it was more easy to reference, I've added those to the list of flags already present under the "Using the compiler" page

Added more common compilation flags

---

guides/testing.md

Took me hours to find this as I am using acme editor which meant I was getting all the all the color commands as junk and you cannot turn off through `export TERM=dumb`. Adding it to the gitbook so others dont struggle.

you can test without colors

---

syntax_and_semantics/macros.md

Add further details on macro processing, specifically within comments. Provides an example of where this may be used, and areas where it may cause confusions for new comers (e.g. me).
Based on discussion in crystal-lang/crystal#8408.

Add section on macro evaluation within comments.

---

conventions/documenting_code.md

Ref: https://github.com/crystal-lang/crystal/pull/6362
Although it is already a valid change.

Use `:ditto:` instead of `ditto`

---

overview/cli.md

I know this is pretty simple, but I think there's no reason to keep this verbose version since Crystal can be so concise and readable.
It could be  `the_beatles.[rand(4)]` too, if you guys want to keep it approachable for non-Ruby users, but I like `sample` more, and probably most users know what it does.

Update algorithm for getting a random array element

---

syntax_and_semantics/case.md

I think marking the "when" keyword as code would make the paragraph easier to understand.
Unedited version: "When a case expression is a tuple literal there are a few semantic differences if a when condition is also a tuple literal."
Edited version: "When a case expression is a tuple literal there are a few semantic differences if a `when` condition is also a tuple literal."

Marked "when" as code in tuple literal paragraph

---

using_the_compiler/README.md

Adds docs for `--project-name` and `--project-version` options for `crystal docs` introduced in https://github.com/crystal-lang/crystal/pull/8792.

Add project info options for crystal docs

---

using_the_compiler/README.md

It is `crystal eval` section, but it was `crystal build --help`.
So, it is fixed.
Thank you.

Fix typo in `crystal eval` section

---

syntax_and_semantics/literals/integers.md

When both side of vertical bar `|` of table is missing, the translation tool (Okapi framework) fails on parsing this table.
See screen shot:
I think it is a bug of [Markdown library Okapi uses](https://github.com/vsch/flexmark-java). However it is little fix, and it does not effect readability. Please merge it for Japanese Crystal users :pray:

Modify table format

---

database/README.md

The previous trailing note was not visible enough when skimming the document.

Database guide: Highlight different syntax for query parameters

---

syntax_and_semantics/type_grammar.md

For instance, the following code is valid:
```crystal
p Int32? # => Int32 | Nil
```
And it is used [here](https://github.com/crystal-lang/crystal/blob/2cbe65b0a13c8a2ce91bd4799f5b96b8e1953097/src/array.cr#L1774).

Fix wrong description of `Int32?` in regular code

---

syntax_and_semantics/not.md

See, for example, https://en.wikipedia.org/wiki/Truthiness

Use proper spelling for the word truthiness

---

syntax_and_semantics/literals/symbol.md

As explained in the text below, a symbol can contain Unicode codepoints.
Provide an example to prove the point.

Provide an example of a symbol with Unicode codepoint

---

getting_started/cli.md

In the current version of the book, examples are indicated to be compiled-and-run with the following syntax
```shell-session
crystal ./help.cr -- -h
```
which doesn't do what is expected for the reader: the `-h` option does not have effect

Getting started: replace compile-and-run syntax for 'crystal run'

---

SUMMARY.md
syntax_and_semantics/blocks_performance.md
syntax_and_semantics/proc_pointer.md

Pages that are never linked to are impossible to view, and MkDocs would've complained about that.

Restore the page overview/README.md, delete all unused & empty pages

---

docs/conventions/documenting_code.md
docs/database/transactions.md
docs/getting_started/README.md
docs/guides/ci/circleci.md
docs/guides/ci/travis.md
docs/guides/hosting/github.md
docs/guides/writing_shards.md
docs/syntax_and_semantics/annotations.md
docs/syntax_and_semantics/as.md
docs/syntax_and_semantics/c_bindings/fun.md
docs/syntax_and_semantics/literals/range.md
docs/using_the_compiler/README.md
mkdocs.yml

This is made possible by mkdocs, but is certainly not a required change.
It's up to you whether you like this style change.
Preview: https://oprypin.github.io/crystal-book/guides/hosting/github.html
Reference: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

Use actual admonition syntax for "NOTE:"

---

docs/conventions/documenting_code.md
docs/getting_started/http_server.md
docs/guides/hosting/github.md

This is not directly related to MkDocs, just an improvement. Although Gitbook's parser did kinda botch this if this change was applied.
Preview: https://oprypin.github.io/crystal-book/conventions/documenting_code.html

Properly indent paragraphs that should be part of a list

---

docs/syntax_and_semantics/operators.md

Rendering was broken in gitbook, but now properly works with mkdocs

Convert tables in operators.md to markdown

---

docs/SUMMARY.md
docs/guides/static_linking.md
docs/using_the_compiler/README.md

The original content is at https://github.com/crystal-lang/crystal/wiki/Static-Linking but should be moved to a more public location and fits very well as a guid (see https://forum.crystal-lang.org/t/overhauling-the-github-wiki/1303).
I also enhanced the content with more explicitly outlining the specifics of fully static linking.

Import Static Linking guide from GH wiki

---

docs/guides/performance.md

The Markdown spec requires that multiple paragraphs within a list item be indented 4 spaces or 1 tab, as does MkDocs (via the `markdown` package).
This was causing a display issue in the rendered site.
---
Before
---
After

Indent list item paragraphs in performance guide

---

docs/assets/style.css

The font size in admonition paragraphs is very small at 80% of regular body copy. This actually makes it hard to read in comparison.
This patch increases the font size to 90% of regular paragraphs:

Increase font size in admonitions

---

syntax_and_semantics/unless.md

Was counterintuitive in the `if` statement about the naming of the "else_expression" in the "then" block

Update unless.md, change then/else block terms

---

docs/syntax_and_semantics/case.md

I don't see it being mentioned in this repo at all, so I added some minimal examples for `case in` expressions.

Add docs for exhaustive case expressions

---

syntax_and_semantics/cross-compilation.md

Took a lot of googling to find out how to cross compile for an aarch64 machine, wanted to share the script I now use. It's not the most generic but for Ubuntu machines it works..

Cross compiling example

---

docs/README.md

The page https://crystal-lang.org/reference/ has a link "Language Reference", which points to https://crystal-lang.org/reference/syntax-and-semantics/, but that link does not work. It should be https://crystal-lang.org/reference/syntax_and_semantics instead
I fixed this by replacing "-" by "_" in docs/README.md

Fix link to Syntax and Semantics page

---

.github/workflows/deploy-book.yml
Makefile
docs/README.md
docs/database/connection.md
docs/getting_started/cli.md
docs/guides/ci/README.md
docs/guides/ci/travis.md

In CI, use regular expressions to check against the kinds of links that could be made safer by letting MkDocs check their validity:
* Links not ending with '.md' (but the check is specifically for '.html' and '/' endings)
* Links starting with '/' or containing the site URL itself.
Closes #498

Disallow unchecked intra-site links

---

docs/syntax_and_semantics/operators.md

fixes #510 
As discussed in #510, the compiler allows to chain some of the comparisons and equality together but this was not documented yet.  
In this PR, I now added a little section about this.
I also investigated this a little more and noticed that in some cases compile time errors occur, e.g. for `a <= b == c`.
This is because the precedence handling (I think this is done here: https://github.com/crystal-lang/crystal/blob/a7544b5f0f3e23d05cb4622ff4db3cbb7f1b996a/src/compiler/crystal/syntax/parser.cr#L537) interferes with the normalization (https://github.com/crystal-lang/crystal/blob/a7544b5f0f3e23d05cb4622ff4db3cbb7f1b996a/src/compiler/crystal/semantic/normalizer.cr#L100).
I tried to describe this a little bit in the documentation as well.
Probably it is worthwhile to discuss this …

Add documentation for chaining of comparisons and equalities

---

docs/syntax_and_semantics/capturing_blocks.md
docs/syntax_and_semantics/literals/proc.md

`Void` is a construct that is only relevant to C bindings. Referencing it outside of that explicit context could be confusing, and could lead people to use it where it's not meant to be used. (Evidence: me, about a year and a half ago :stuck_out_tongue:)

Remove Void outside of references to C code

---

docs/syntax_and_semantics/macros/README.md

To be merged once the corresponding [PR](https://github.com/crystal-lang/crystal/pull/10682) gets merged.

Add docs for `@top_level` macro variable

---

docs/syntax_and_semantics/macros/README.md

the code within a block in the macros file was not properly formatted.

fixing the formatting of macros

---

docs/guides/performance.md

This PR fixes a typo in an example block declaration that prevented the file name being displayed correctly above the example code.
Before:
After:

Fix type in performance.md example block

---

.github/workflows/deploy-book.yml
docs/guides/ci/gh-actions.md

It was moved to this org, as https://github.com/crystal-lang/install-crystal

Use the new location of install-crystal GitHub Action

---

docs/syntax_and_semantics/operators.md

`puts 2 ** 3 ** 2` results in `512`.  Repeated exponentiation is parsed as right-associative, as in `puts 2 ** (3 ** 2)`.
The crystal language implements this correctly.  This is just a documentation fix.

Exponentiation operators should have right associativity

---

.github/workflows/deploy-book.yml
Makefile

* `pip` works slightly faster with `--no-deps`, and our deps are always fully resolved.
* Seems like when installing `mkdocs`, its executable would have an old mtime, then the site is always considered outdated as it depends on the executable.
* GH workflow: split out the deps step for timing measurement purposes
* `check_internal_links` is not a file target

Improve Makefile

---

requirements.in
requirements.txt

Due to a bug, redirects to "README.md" are no longer recognized correctly as "index.html":
https://github.com/datarobot/mkdocs-redirects/issues/23

Downgrade mkdocs-redirects plugin back to an older version

---

docs/syntax_and_semantics/documenting_code.md

`EXPERIMENTAL` was missing (only the corresponding annotation is mentioned). `WARNING` is due to crystal-lang/crystal#10898.

Update list of admonition keywords

---

docs/syntax_and_semantics/literals/array.md
docs/syntax_and_semantics/literals/tuple.md

Add wording for crystal-lang/crystal#10429.

Add documentation for splat expansions in array / tuple literals

---

docs/platform_support.md

We're experiencing issues with running the automated tests on i386-linux-gnu (see crystal-lang/crystal#11127) and that's unlikely to change anytime soon.

Demote i386-linux-gnu to Tier 2

---

docs/syntax_and_semantics/literals/char.md
docs/syntax_and_semantics/literals/string.md

The missing documentation of `'\0'` was discovered in #11260
I cross-checked with the lexer and noticed escaped hash character (`"\#"`) is also missing for string literals.
Now all escape sequences should be properly documented.

Document null and hash character escape sequences in char and string literals

---

docs/syntax_and_semantics/macros/README.md

I noticed that this section was copy-pasted from the previous one, but since it's supposed to demonstrate `verbatim`, this part was incorrectly left unchanged.

Fix incorrect example of macro expansion

---

docs/guides/writing_shards.md

CrystalShards.xyz is down once again. CrystalShards.org is more stable and has not experienced downtime in the last few years.

Update crystal shards location

---

.github/workflows/deploy-book.yml
scripts/docs-versions.sh

Use branch names like 'release/1.2' for versioned deployment

---

.github/workflows/deploy-book.yml
hooks.py

Reverts #562:
the replacement of API doc links works incorrectly for `master` (puts the commit hash), although it works for versioned releases

Revert "Use the version of Crystal according to the current branch"

---

.github/workflows/deploy-book.yml
hooks.py

Currently pull requests don't see a valid branch name, so the selection of Crystal version (to validate against) doesn't work at all for them.
This is a fixup for #562

Reland: Use the version of Crystal according to the current branch

---

.github/workflows/deploy-book.yml

Note:
* The original file is kept even though it won't be manually updated anymore.
* The `crystal` invocation is kept separate from the build process.
This ensures that 'crystal-book' doesn't have 'crystal' as a hard build dependency.
---
Ref https://github.com/crystal-lang/crystal-book/pull/578#issuecomment-1007216153
Made possible by https://github.com/crystal-lang/crystal-book/pull/562

Automatically populate crystal-version.txt

---

docs/guides/testing.md

this fixes the following error:
```
actual_value.same? @expected_value
^----
Error: undefined method 'same?' for Bool
```

fix bool error in spec example

---

docs/using_the_compiler/README.md

The flag for ThinLTO was dropped in https://github.com/crystal-lang/crystal/pull/11194. This change removes that flag from the Crystal reference documentation.

Remove reference to ThinLTO

---

docs/README.md

These are relevant resources for *Getting started* and there were no direct links so far.

Add links for *Install* and *Try Online* to home page

---

docs/README.md
docs/SUMMARY.md

The sidebar navigation seems out of place on the homepage because the site itself is already a big navigation hub with links to all pages in its section. Having those links duplicated in the sidebar nav is confusing. It looks like those links are more important in the context than the rest of the page, which is not the case. It's a landing page for all the content in the Crystal Book.
The sidebar navigation stays visible on pages in the section (see https://deploy-preview-592--crystal-book.netlify.app/platform_support.html for example).
The page title gets renamed from *Home* to *Welcome* in order to avoid confusion with the Crystal home page at https://crystal-lang.org/
Alternative names could be *Index*  or *Table of Contents* but they don't feel as welcoming... 😁

Rename homepage to *Welcome* and hide navigation bar

---

docs/assets/style.css

It seems otherwise we'd have to keep adding !important in more and more places as a game of whack-a-mole.
This time the override for margins of `li` and `ul` elements got disrupted.
This regressed in https://github.com/crystal-lang/crystal-book/pull/599
Good: https://crystal-lang.org/reference/1.2/
Bad: https://crystal-lang.org/reference/1.4/

Fix: increase specificity of .card CSS

---

docs/assets/vendor/carcin-play/codemirror-theme.css

In this PR we fix the font size when using crystal-play code-blocks.
The size is the same as other code-blocks (define with ```crystal) in the book. 
Also using a smaller font makes the code-block fit well with the text.

Fix font size of crystal-play blocks

---

docs/tutorials/basics/60_methods.md

All the examples in `Tutorial>Methods` show methods that don't return a value.
We added new examples of methods returning values and also, examples with return type information

Add Return section to Tutorial > Methods

---

docs/syntax_and_semantics/generics.md

After adding https://github.com/crystal-lang/crystal/pull/11906 to Crystal 1.4, it's a good time to add definitions and examples for "using splats in generics" to the Generics section.
The last example shows the _Support Generic nodes with no type variables_

Add Generics with variable number of arguments

---

docs/database/README.md

Mention postgres can take a user/pass, though ideally wouldn't this just be described in the individual modules?

Mention user:password for PostgreSQL

---

docs/database/README.md

Add example of query parameters in a query, mention there are more helper methods available for query, mention preparedstatements are at play (crystal-lang/crystal-db#164).

Update DB Readme

---

docs/tutorials/basics/50_control_flow.md

This section has been brewing for long and I finally managed to finish it up after a nudge in #581.
It only covers the basic building blocks `while`, `until`, `next` and `break`. The more convenient looping methods from stdlib will be introduced in a later lesson. The tutorial still misses a couple of basic concepts for that.

Add section about loops in basic tutorial

---

docs/platform_support.md

Basic WebAssembly support has been added in https://github.com/crystal-lang/crystal/pull/10870 and was released in Crystal 1.4
The second commit applies uniform format for the libc description.

Add WASM to platform support list

---

docs/syntax_and_semantics/if_var_nil.md

This has tripped me up enough times that I assume others are experiencing the same issue, so I wanted to add more information to the page on type restriction through `if var.nil?`.

Add note about type coercion of instance variables

---

docs/guides/testing.md
requirements.in
requirements.txt

by bumping mkdocs-code-validator which was preventing titles from being recognized at all.
https://github.com/oprypin/mkdocs-code-validator/commit/2e37afbb44cbcf39f242ae98ee68650a82342f76
Also replace remaining old usages of titles.

Fix display of `title=` at the top of code blocks

---

docs/database/transactions.md
docs/getting_started/README.md
docs/guides/ci/circleci.md
docs/guides/ci/gh-actions.md
docs/guides/hosting/github.md
docs/guides/static_linking.md
docs/guides/writing_shards.md
docs/syntax_and_semantics/annotations/README.md
docs/syntax_and_semantics/as.md
docs/syntax_and_semantics/c_bindings/fun.md
docs/syntax_and_semantics/documenting_code.md
docs/syntax_and_semantics/literals/range.md
docs/tutorials/basics/10_hello_world.md
docs/tutorials/basics/20_variables.md
docs/tutorials/basics/30_math.md
docs/tutorials/basics/40_strings.md
docs/tutorials/basics/50_control_flow.md
docs/tutorials/basics/60_methods.md
docs/using_the_compiler/README.md
mkdocs.yml
requirements.in
requirements.txt

The result is exactly equivalent, just different syntax -- one that doesn't look weird in vanilla Markdown parsers such as on GitHub.
https://github.com/oprypin/markdown-callouts

Switch syntax of admonitions to "markdown-callouts" extension

---

docs/syntax_and_semantics/annotations/README.md
docs/syntax_and_semantics/macros/README.md

* Document annotations on method parameters added in https://github.com/crystal-lang/crystal/pull/12044
* Document `parse_type` method added in https://github.com/crystal-lang/crystal/pull/11126
Depends on https://github.com/crystal-lang/crystal/pull/12446

Document new annotation/macro features

---

docs/README.md
mkdocs.yml

The page URL for the website requires the `.html` suffix, it's not optional.
We should change that in the deployment, but for now this is the easiest fix to make the link work.

Fix link to governance document

---

docs/database/README.md

From crystal-lang/crystal-db#164

Add prepared statement example, etc

---

docs/syntax_and_semantics/c_bindings/lib.md

cf. https://github.com/crystal-lang/crystal/pull/12848

Add section about `lib` function visibility in macro

---

docs/syntax_and_semantics/generics.md

Makes it clear that this feature is not exclusive to constructors (`.new`).
I believe that this is indeed intended behavior, as the standard library makes use of it for class methods other than `.new` already, even when the type variable is not part of a block parameter restriction (where type inference works slightly differently):
```crystal
struct Pointer(T)
def self.malloc(size : Int, value : T)
ptr = Pointer(T).malloc(size)
size.times { |i| ptr[i] = value }
ptr
end
end
module Iterator(T)
def self.of(element : T) 
SingletonIterator(T).new(element) 
end 
end
```

Elaborate on type variable inference of generic class methods

---

docs/syntax_and_semantics/compile_time_flags.md

PCRE is the default engine in 1.8.0 with fallback to PCRE if unavailable (https://github.com/crystal-lang/crystal/pull/12978).

Add `use_pcre` stdlib flag

---

docs/syntax_and_semantics/compile_time_flags.md
docs/syntax_and_semantics/platform_support.md

Basic Android support was added in https://github.com/crystal-lang/crystal/pull/13065

Add platform android

---

docs/syntax_and_semantics/platform_support.md
mkdocs.yml

Enhance information about minimum supported versions and limitations of lower-tier platforms.
Resolves crystal-lang/crystal#13170

Update platform support

---

docs/conventions/coding_style.md

This adds an official style guide for what is previously only an informal convention in the standard library. See crystal-lang/crystal#13400.

Require exception messages to be sentence-cased

---

docs/crystal_for_rubyists/README.md

This adds an explicit section about the shorthand hash syntax from Ruby defining a NamedTuple in Crystal to help avoid some syntax confusion between the languages.

Add section about Hash syntaxes in Crystal for Rubyists

---

docs/syntax_and_semantics/case.md
docs/syntax_and_semantics/operators.md

The main purpose is to separate the pattern matching and case subsumption operators (`=~`, `!~` and `===`) from the equality operators (`==`, `!=`). They are *not* about equality. The case subsumption operator should also not be called *case equality* because it's misleading. 
The entire group of operators including equality, subsumption and inequalities is called relational operators.
In the process of this restructuring I've also reworded and enhanced the descriptions for these operators with the purpose of adding clarity and filling gaps. Also added some references to related features in the standard library.
The result is still a bit thin in some areas (especially regarding pattern matching and case subsumption) but I'm not sure about some of the specific details myself. We'll need to …

Rework section about relational operators

---

docs/man/shards/README.md

The title says it all, I basically took the man page info and just added an example. This should make it a lot easier for users to find.

Adds basic info about shard.override.yml file to `shards` command page

---

.envrc
.github/workflows/deploy-book.yml
.gitignore
Makefile
README.md
devenv.lock
devenv.nix
devenv.yaml
docs/syntax_and_semantics/operators.md

This sets up a reproducible development environment via [devenv.sh](https://devenv.sh).
Using it is completely optional, but I've come to like it as a tool that ensures the working environment is consistent and functional.
Usage instructions are added to the readme.
The first two commits are independent preconditions:
* markdownlint-cli@0.34.0 complains about spaces inside code span elements. As a mitigation this test is deactivated for the affected code.
* Resolution of python dependencies has been removed from the Makefile. That was a rather odd thing and has been bugging me for some time. We shouldn't dictate the use of pip and venv for python dependencies. The makefile should only require that `mkdocs` is available. Previously it was impossible to install dependencies in a different …

Add devenv

---

docs/man/crystal/README.md

The compiler command was added in https://github.com/crystal-lang/crystal/pull/13553

Add manual entry for `crystal clear_cache`

---

docs/syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.md

`syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.html#external-names` gives an example using non-existent function `Time.now`. Replaced with `Time.local`.
Thank you @Blacksmoke16 for pointing it out and encouraging me to make a small PR! :smiley:

Fix `Time.local` instead of `Time.now` in example

---

docs/syntax_and_semantics/annotations/README.md
docs/syntax_and_semantics/documenting_code.md
hooks.py
mkdocs.yml
requirements.in
requirements.txt

* Use new native link validation, making some code obsolete.
* Fix a few links that are recognized as invalid.
* Enable validation for missing paths in pymdownx.snippets.
* Exclude SUMMARY.html from the built site.

Upgrade MkDocs version, related updates

---

docs/syntax_and_semantics/enum.md

Better enum symbol casting documentation

---

docs/man/required_libraries.md

fix typo `Regular Exception engine` -> `Regular Expression engine`

Fix typo in `required_libraries.md`

---

mkdocs.yml

This adds an "Edit this page" button on every page to facilitate easy access for contributing.
The `edit_uri` was already configured (although with a view url, not edit), but the actual edit button needs to be enabled as well.

Enable edit link

---

docs/syntax_and_semantics/blocks_and_procs.md

Unlimited block unpacking was introduced in https://github.com/crystal-lang/crystal/pull/11597

Add docs for unlimited block unpacking

---

docs/man/crystal/README.md

Updates the manual with respect to the changes from
* https://github.com/crystal-lang/crystal/pull/13930
* https://github.com/crystal-lang/crystal/pull/13927
* https://github.com/crystal-lang/crystal/pull/13929
* https://github.com/crystal-lang/crystal/pull/13926
* https://github.com/crystal-lang/crystal/pull/13969

Add new unreachable options to compiler manual

---

docs/man/crystal/README.md
docs/syntax_and_semantics/compile_time_flags.md

Updates the manual with respect to the changes from https://github.com/crystal-lang/crystal/pull/13464

Add optimization levels to compiler manual

---

docs/man/crystal/README.md

Updates the manual with respect to the changes from https://github.com/crystal-lang/crystal/pull/13804 and https://github.com/crystal-lang/crystal/pull/13616 and some further options that have been missing.

Update options for `crystal spec`

---

.github/workflows/deploy-config.yml

There's no need to regenerate config every time a new branch is created. Only release branches are relevant. Other branches do not deploy.

Run `deploy config` workflow only when a release branch is created

---

docs/syntax_and_semantics/class_methods.md

I suspect calling a class method from an instance method is common.  At least it is in some of the Ruby code I've worked on.  I hope that this example is helpful.
I think the sentence immediately before this in the docs could be a little bit confusing: "When called from within the same class or module scope the receiver can be `self` or implicit".  The key-word in there is `scope`, but if one misses that word its easy to conclude (incorrectly) that one can simply call `self.class_method` from an instance method.

Add example of accessing class method from instance method

---

.github/workflows/deploy-book.yml

Currently, `edit_uri` always points to the master branch. This is confusing when you're on a release branch because the contents may differ. Release branches (especially the latest one) is the main deployed version and you won't see the master deployment unless you explicitly chose the "nightly" version.
Example for confusion: https://github.com/crystal-lang/crystal/pull/11876#issuecomment-1902599532

Set `edit_uri` to point to deployed branch

---

.github/workflows/validate-content.yml
scripts/validate-flags.sh

This script extracts all `flag?` macro values from the source code and compares them with the documentation.
It lists all flags that are currently defined but undocumented.
It depends on `crystal tool flags`, proposed in https://github.com/crystal-lang/crystal/pull/14234
<del>This could be automated in CI to check flag documentation regularly.</del>
<ins>Adds a CI workflow that regularly checks flag documentation coverage.</ins>

Add `scripts/validate-flags.sh`

---

docs/syntax_and_semantics/alignof.md
docs/syntax_and_semantics/instance_alignof.md
docs/syntax_and_semantics/instance_sizeof.md
docs/syntax_and_semantics/sizeof.md

Applies the improvements mentioned in https://github.com/crystal-lang/crystal-book/pull/728#pullrequestreview-1800694828 across all pages.

Improve wording on alignof and sizeof pages

---

docs/syntax_and_semantics/platform_support.md

Solaris support was added in https://github.com/crystal-lang/crystal/pull/14343

Add Solaris/illumos to *Platform Support*

---

docs/syntax_and_semantics/compile_time_flags.md

Follow-up to #750 which added Solaris to *Platform Support*, but we als got a new compiler flag.

Add compile time flag `solaris`

---

docs/syntax_and_semantics/compile_time_flags.md

This change separates flags that you pass to the compiler when building a Crystal program from flags you pass for building the compiler specifically.
Also moves some incorrectly categorized flags between compiler and stdlib features.

Reorganize compile time flags for the compiler

---

docs/README.md
docs/SUMMARY.md
docs/project/release-policy.md

Resolves https://github.com/crystal-lang/crystal/issues/14481
The content is heavily based on [hexdocs.pm/elixir/compatibility-and-deprecations.html](https://hexdocs.pm/elixir/compatibility-and-deprecations.html), which is a great summary especially concerning backwards compatibility and matches the intentions of the Crystal project (as far as I'm concerned).

Add page *Release Policy*

---

docs/syntax_and_semantics/compile_time_flags.md

This was added in https://github.com/crystal-lang/crystal/pull/14393

Add flag for `avr` architecture

---

docs/getting_started/cli.md

Follow up to https://github.com/crystal-lang/crystal-book/pull/624 to also handle `crystalshards.org`.

Remove references to `crystalshards.org`

---

docs/syntax_and_semantics/exception_handling.md

Module types were added in https://github.com/crystal-lang/crystal/pull/14552

Mention which types are valid for type restriction on `rescue`

---

docs/syntax_and_semantics/platform_support.md

AVR support was added in https://github.com/crystal-lang/crystal/pull/14393

Add AVR target to *Platform Support*

---

docs/syntax_and_semantics/platform_support.md

Since https://github.com/crystal-lang/crystal/pull/14833 we have automated tests for `aarch64-darwin` in CI.
That was the only thing missing for Tier 1, so now we can promote it.

Promote `aarch64-darwin` to Tier 1

---

docs/syntax_and_semantics/platform_support.md

For crystal-lang/crystal#14911

Add ARM64 Windows to list of supported platforms

---

docs/syntax_and_semantics/operators.md

Exclusive range is labelled explicitly, but `..` isn't.

Update range section of operators page to specify inclusivity

---

docs/syntax_and_semantics/modules.md

Currently, `Three` inherits `Two`, and thus B, but it simply includes `A`, just like `One`.
The explanation is not consequent with this, as both `One` and `Three` simply `include A`.
```cr
new_array << one   # Ok, One inherits module A
new_array << three # Ok, Three includes module A
```
The changes should reflect the difference between directly including a module, and inheriting the inclusion from a class.

Updates module inclusion / inheritance example

---

docs/guides/static_linking.md
docs/syntax_and_semantics/compile_time_flags.md

Dynamic linking has been the default for MSVC since Crystal 1.12.0 (crystal-lang/crystal#14292).

Remove mentions of `-Dpreview_dll`

---

docs/guides/static_linking.md
docs/syntax_and_semantics/compile_time_flags.md

This entire section describes the obsolete behavior of `CRYSTAL_LIBRARY_RPATH` that has been removed since Crystal 1.13 (crystal-lang/crystal#14598).

Remove the "Dynamic library lookup" section

---

.github/workflows/validate-content.yml
scripts/validate-flags.sh

* Check out the Crystal repo associated with the target branch (`release/1.14` for `release/1.14`).
* Run workflow only on `ubuntu-latest`. There's no reason to run this on different platforms. `crystal tool flags` operates on the raw source code and does not take platform differences into account.
* Run workflow only when `docs/syntax_and_semantics/compile_time_flags.md` is changed to avoid noise in unrelated PRs

[CI] Refactor `Validate Flags` workflow

---

docs/syntax_and_semantics/annotations/README.md
docs/syntax_and_semantics/block_forwarding.md
docs/syntax_and_semantics/c_bindings/callbacks.md
docs/syntax_and_semantics/closures.md
docs/syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.md
docs/syntax_and_semantics/if_var.md
docs/syntax_and_semantics/literals/proc.md
docs/syntax_and_semantics/type_restrictions.md

Crystal nightly has a couple new formatter rules enabled: https://github.com/crystal-lang/crystal/pull/14718
The changes are backwards-compatible, so Crystal 1.14.0 won't complain about the new format.

`crystal tool format` with Crystal 1.15.0-dev

---

docs/syntax_and_semantics/macros/hooks.md

We can "stack" (not sure what else to call it) certain macro hooks like `finished` but something like `method_missing` will override previous macro hooks in the same context. Feel free to rename or whatever. 👍🏻

Add examples on "stacking" and "overriding" certain macro hooks

---

docs/man/required_libraries.md

Adds information about supported library versions, as taken from https://github.com/crystal-lang/crystal/pull/14900

Add library versions

---

docs/crystal_for_rubyists/README.md

The `previous_def` keyword was missing in the [Available keywords](https://crystal-lang.org/reference/1.14/crystal_for_rubyists/index.html#available-keywords) section.
There are the sources where this keyword was used :
- https://crystal-lang.org/reference/1.14/syntax_and_semantics/methods_and_instance_variables.html#redefining-methods-and-previous_def
- https://crystal-lang.org/reference/1.14/crystal_for_rubyists/metaprogramming_help.html#crystal-approach-to-alias_method

Add the missing `previous_def` keyword into "Available keywords" section.

---

docs/syntax_and_semantics/platform_support.md

Bump the minimum version after crystal-lang/crystal#15335

Update minimum Linux kernel version 2.6.22

---

docs/syntax_and_semantics/operators.md

There is some disagreement between Markdown parsers about escaping pipe characters (`|`) inside a table cell. Python-markdown, which is used by our site generator mkdocs, considers a pipe inside a code span as escaped (`` `|` ``) (https://github.com/Python-Markdown/markdown/issues/436). Most other Markdown parsers, including ones used in tooling (such as markdownlint) require explicit escaping (`` `\|` ``). Python-markdown would render the backslash:
This is a known interoperability issue based on different implementations of a Markdown parser (https://github.com/mkdocs/mkdocs/issues/2761). There's no expectation for this to get fixed somewhow, so we can only apply a workaround to use code that different parsers agree upon: This patch replaces backticks with HTML `<code>` tags, for which …

Fix markdown escape pipe character in table cell

---

docs/syntax_and_semantics/alignof.md
docs/syntax_and_semantics/sizeof.md

c.f. https://github.com/crystal-lang/crystal/pull/15575

Document macro versions of `sizeof` and `alignof`

---

docs/syntax_and_semantics/documenting_code.md

https://github.com/crystal-lang/rfcs/blob/main/text/0011-extending-api-docs.md

Add documentation for `:showdoc:`

---

docs/syntax_and_semantics/platform_support.md

Since crystal-lang/crystal#15794, we're running tests on `aarch64-windows-gnu` and produce release builds

Bump support for `aarch64-windows-gnu`
